apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rohanakode490/fc-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_JWT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEXT_PUBLIC_JWT_PASSWORD
            - name: NEXT_PUBLIC_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEXT_PUBLIC_BACKEND_URL
            - name: NEXT_PUBLIC_HOOKS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEXT_PUBLIC_HOOKS_URL
            - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary-backend
  template:
    metadata:
      labels:
        app: primary-backend
    spec:
      containers:
        - name: primary-backend
          image: rohanakode490/fc-primary-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: FRONTEND_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
            - name: JWT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_PASSWORD
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SESSION_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GITHUB_CLIENT_SECRET
            - name: TOGETHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TOGETHER_API_KEY
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: primary-backend
  namespace: default
spec:
  selector:
    app: primary-backend
  ports:
    - port: 80
      targetPort: 4000
      nodePort: 32130
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooks
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooks
  template:
    metadata:
      labels:
        app: hooks
    spec:
      containers:
        - name: hooks
          image: rohanakode490/fc-hooks:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: LINKEDIN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: LINKEDIN
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hooks
  namespace: default
spec:
  selector:
    app: hooks
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 31294
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: rohanakode490/fc-processor:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: KAFKA_BROKERS
              value: "my-kafka-kafka-bootstrap.default.svc.cluster.local:9092"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: processor
  namespace: default
spec:
  selector:
    app: processor
  ports:
    - port: 80
      targetPort: 6000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: rohanakode490/fc-worker:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: KAFKA_BROKERS
              value: "my-kafka-kafka-bootstrap.default.svc.cluster.local:9092"
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RESEND_API_KEY
            - name: SOLANA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SOLANA_PRIVATE_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: default
spec:
  selector:
    app: worker
  ports:
    - port: 80
      targetPort: 7000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
# Strimzi Kafka Custom Resource (replaces manual Kafka and ZooKeeper deployments/services)
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
  namespace: default
spec:
  kafka:
    version: 3.9.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      auto.create.topics.enable: true
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  entityOperator:
    topicOperator: {}
    userOperator: {}

